spring.application.name=api_rest_security

##Configuracion de base de datos
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

##Configuracion de perfiles
spring.profiles.default=dev